"""Extraction accuracy against ground truth.

    uv run python scripts/accuracy.py [corpus_dir ...]      # default: ../corpus/synthetic ../corpus/real

For every PDF with a sibling *.truth.json it reports:
  recall        share of ground-truth figures found at the right place
  exact         share of found figures whose raw string matches the PDF exactly
  labels        share of table cells with the correct row AND column label
  precision     share of extracted figures that correspond to a ground-truth figure
Writes ../corpus/ACCURACY.md as well.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.extraction.schema_builder import extract  # noqa: E402
from app.extraction.tokens import _split_punct  # noqa: E402

CORPUS = ROOT.parent / "corpus"


def _core(raw: str) -> str:
    return _split_punct(raw)[1]


def _norm(s: str | None) -> str:
    return " ".join((s or "").split()).lower()


def _center_in(b, box, pad=2.0) -> bool:
    cx, cy = (b[0] + b[2]) / 2, (b[1] + b[3]) / 2
    return box[0] - pad <= cx <= box[2] + pad and box[1] - pad <= cy <= box[3] + pad


def evaluate(pdf: Path) -> dict:
    truth = json.loads(pdf.with_suffix(".truth.json").read_text())
    meta = truth.get("metadata") or {"company_name": "Sample", "report_type": "quarterly_results",
                                     "fiscal_year": 2026, "period": "q2", "currency": "INR",
                                     "reporting_unit": "₹ crore", "filename": pdf.name}
    schema, _ = extract(pdf.read_bytes(), meta)
    figs = list(schema["figures"].values())
    gt = truth["figures"]
    found = exact = cells = cell_labels_ok = 0
    matched_fids: set[str] = set()
    misses = []
    for g in gt:
        core = _core(g["raw"])
        cands = [f for f in figs if f["source"]["page"] == g["page"] and
                 (_center_in(f["source"]["bbox"], g["bbox"], 3) or _center_in(g["bbox"], f["source"]["bbox"], 3))
                 and (core in f["raw"] or f["raw"] in core)]
        if not cands:
            misses.append(f"p{g['page']} {g['raw']!r} ({g.get('role', 'text')})")
            continue
        f = min(cands, key=lambda f: abs(len(f["raw"]) - len(core)))
        found += 1
        matched_fids.add(f["id"])
        if core in f["raw"].split(" ") or f["raw"] == core:
            exact += 1
        if g.get("role") == "cell":
            cells += 1
            if _norm(f.get("row_label")) == _norm(g["row_label"]) and _norm(f.get("col_label")) == _norm(g["col_label"]):
                cell_labels_ok += 1
    precision_hits = sum(1 for f in figs if f["id"] in matched_fids)
    methods = sorted(set(schema["metadata"]["extraction"]["methods"].values()))
    return {
        "file": pdf.name, "methods": methods, "truth": len(gt), "extracted": len(figs),
        "recall": found / len(gt) if gt else 1.0,
        "exact": exact / found if found else 0.0,
        "labels": cell_labels_ok / cells if cells else None,
        "precision": precision_hits / len(figs) if figs else 0.0,
        "misses": misses[:15],
        "charts": [(b["source"]["page"], b["extracted"]) for s in schema["sections"] for b in s["blocks"] if b["type"] == "chart"],
        "tables": sum(1 for s in schema["sections"] for b in s["blocks"] if b["type"] == "table"),
        "sections": [(s["type"], s["heading_text"]) for s in schema["sections"]],
    }


def main(dirs: list[str]) -> None:
    paths = [Path(d) for d in dirs] or [CORPUS / "synthetic", CORPUS / "real"]
    results = [evaluate(pdf) for d in paths if d.exists() for pdf in sorted(d.glob("*.pdf"))
               if pdf.with_suffix(".truth.json").exists()]
    lines = ["# Extraction accuracy", "", "| File | Method | Figures (truth / extracted) | Recall | Exact raw | Cell labels | Precision |",
             "| --- | --- | --- | --- | --- | --- | --- |"]
    for r in results:
        lab = f"{r['labels']:.1%}" if r["labels"] is not None else "—"
        lines.append(f"| {r['file']} | {', '.join(r['methods'])} | {r['truth']} / {r['extracted']} | {r['recall']:.1%} | "
                     f"{r['exact']:.1%} | {lab} | {r['precision']:.1%} |")
    lines.append("")
    for r in results:
        lines.append(f"## {r['file']}")
        lines.append(f"- tables: {r['tables']}; charts (page, extracted): {r['charts']}")
        lines.append(f"- sections: {r['sections']}")
        if r["misses"]:
            lines.append(f"- missed (first 15): {', '.join(r['misses'])}")
        lines.append("")
    text = "\n".join(lines)
    print(text)
    (CORPUS / "ACCURACY.md").write_text(text + "\n_Synthetic samples are generated by scripts/make_corpus.py; "
                                        "they are not real filings._\n")


if __name__ == "__main__":
    main(sys.argv[1:])
